language: bash
arch:
  - arm64

services:
  - docker

script:
  - docker build -t pestotoast/cadvisor-arm .
  - echo "$DOCKER_PASSWORD" | docker login -u pestotoast --password-stdin
  - docker push pestotoast/cadvisor-arm:latest
